src/Mickweb/EcommerceBundle/Entity/Image.php
<?php

namespace Mickweb\EcommerceBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * Image
 *
 * @ORM\Table(name="image")
 * @ORM\Entity(repositoryClass="Mickweb\EcommerceBundle\Repository\ImageRepository")
 * @ORM\HasLifecycleCallbacks
 */
class Image
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="url", type="string", length=255)
     */
    private $url;

    /**
     * @var string
     *
     * @ORM\Column(name="alt", type="string", length=255)
     */
    private $alt;

    /**************************************/
    private $file;

    // attribut qui stocke le nom du fichier temporairement
    private $tempFilename;


    /**
     * Get id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set url.
     *
     * @param string $url
     *
     * @return Image
     */
    public function setUrl($url)
    {
        $this->url = $url;

        return $this;
    }

    /**
     * Get url.
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Set alt.
     *
     * @param string $alt
     *
     * @return Image
     */
    public function setAlt($alt)
    {
        $this->alt = $alt;

        return $this;
    }

    /**
     * Get alt.
     *
     * @return string
     */
    public function getAlt()
    {
        return $this->alt;
    }

    public function getFile()
    {
        return $this->file;
    }

    public function setFile(UploadedFile $file)
    {
        $this->file = $file;

        // verif si on avait deja un fichier pour cette entité
        if (null !== $this->url) {
            // sauvegarde l'extension du fichier pour le supprimer plus tard
            $this->tempFilename = $this->url;

            // reinitialise les valeurs des attributs url et alt
            $this->url = null;
            $this->alt = null;
        }
    }

    /**********************************************/    
    // méthode qui sert à récupérer un fichier
    /**********************************************/ 

    /** 
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function preUpload()
    {
        // si auncun fichier, on ne fait rien
        if (null === $this->file) {
            return;
        }

        //le nom du fichier est son id, on renomme cet attribut "extension" plutot  que "url"
        $this->url = $this->file->guessExtension();

        //génère l'attribut alt de la balise <img>, à la valeur du nom du fichier
        $this->alt = $this->file->getClientOriginalName();
    }
    
    /** 
     * @ORM\PostPersist()
     * @ORM\PostUpdate()
     */
    public function upload()
    {
        // si auncun fichier, on ne fait rien
        if (null === $this->file) {
            return;
        }

        // si on avait un ancien fichier, on le supprime
        if (null !== $this->tempFilename) {
            $oldFile = $this->getUploadRootDir().'/'.$this->id.'.'.$this->tempFilename;
            if (file_exists($oldFile)) {
                unlink($oldFile);
            }
        }

        /*
        // récupère le nom original du fichier 
        $name = $this->file->getClientOriginalName();
        */

        // déplace le fichier dans le repertoire voulu
        $this->file->move(
            $this->getUploadRootDir(),  // repertoire de destination
            $this->id.'.'.$this->url    // nom du fichier à créer, ici "id.extension"
        );

        /*
        // sauvegarde le nom du fichier dans l'attribut $url
        $this->url = $name;

        // crée le futur attribut alt de la balise image
        $this->alt = $name;
        */
    }

    /** 
     * @ORM\PreRemove()
     */
    public function preRemoveUpload()
    {
        // sauvegarde trmporairerement le nom du fichier
        $this->tempFilename = $this->getUploadRootDir().'/'.$this->id.'.'.$this->url;
    }

    /** 
     * @ORM\PostRemove()
     */
    public function RemoveUpload()
    {
        // on a pas accès à l'id, on utilise notre nom sauvegardé
        if (file_exists($this->tempFilename)) {
            // on supprime le fichier
            unlink($this->tempFilename);
        }
    }

    public function getUploadDir()
    {
        // retourne le chemin relatif vers l'image (relatif au repertoire /web)
        return 'uploads/img';
    }

    public function getUploadRootDir()
    {
        // retourne le chemin relatif vers l'image pour notre code PHP
        return __DIR__.'/../../../../web/'.$this->getUploadDir();
    }

    public function getWebPath()
    {
    return $this->getUploadDir().'/'.$this->getId().'.'.$this->getUrl();
    }
}

src/Mickweb/EcommerceBundle/Form/ProductType.php
<?php

namespace Mickweb\EcommerceBundle\Form;

use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Mickweb\EcommerceBundle\Form\ImageType;
use Mickweb\EcommerceBundle\Form\CategoryType;
use Mickweb\EcommerceBundle\Form\TvaType;

class ProductType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('titre',          TextType::class)
            ->add('description',    TextareaType::class)
            ->add('auteur',         TextType::class)
            ->add('published',      CheckboxType::class, array('required' => false))
            ->add('image',          ImageType::class)
            // Le add ci-dessous sert à ajouter une catégorie
            
            // ->add('categories',     CollectionType::class, array(
            //    'entry_type' => CategoryType::class,
            //    'allow_add' => true,
            //    'allow_delete' => true
            // ))
            
            // le add ci-dessous ne fonctionne pas comme je souhaite, il n'ajoute pas la catégorie, a corriger
            ->add('categories',     EntityType::class, array(
                'class'         => 'MickwebEcommerceBundle:Category',
                'choice_label'  => 'name',
                'multiple'      => false,
                'expanded'      => false,
                'mapped'        => true, 
            ))
            ->add('tva',            EntityType::class, array(
                'class'         => 'MickwebEcommerceBundle:tva',
                'choice_label'  => 'nom',
                'multiple'      => false,
                'expanded'      => false,
                'mapped'        => true, 
            ))
            ->add('prix',           MoneyType::class)
            ->add('save',           SubmitType::class)
        ;
    }
    
    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Mickweb\EcommerceBundle\Entity\Product'
        ));
    }

}

src/Mickweb/EcommerceBundle/Controller/ProductController.php
<?php

namespace Mickweb\EcommerceBundle\Controller;

use Mickweb\EcommerceBundle\Entity\Product;
use Mickweb\EcommerceBundle\Entity\Image;
use Mickweb\EcommerceBundle\Entity\Avis;
use Mickweb\EcommerceBundle\Entity\Category;
use Mickweb\EcommerceBundle\Entity\tva;
use Mickweb\EcommerceBundle\Entity\Commande;
use Mickweb\EcommerceBundle\Entity\PropertySearch;
use Mickweb\EcommerceBundle\Entity\Contact;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Component\Form\Form;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\RequestStack;
//use Symfony\Component\Security\Core\Exception\AccessDeniedException;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\FormType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Mickweb\EcommerceBundle\Form\ProductType;
use Mickweb\EcommerceBundle\Form\ProductModifierType;
use Mickweb\EcommerceBundle\Form\RechercheType;
use Mickweb\EcommerceBundle\Form\AvisType;
use Mickweb\EcommerceBundle\Form\PropertySearchType;
use Mickweb\EcommerceBundle\Form\ContactType;
use Mickweb\EcommerceBundle\Notification\ContactNotification;

class ProductController extends Controller
{
/*******************************PAGE D'ACCUEIL DES PRODUITS****************************************************************/
    public function indexAction($page, Request $request, Category $categories = null)
    {
        $search = new PropertySearch();
        $form = $this->createForm(PropertySearchType::class, $search);
        $form->handleRequest($request);
        
        $session = $request->getSession();
          $em = $this->getDoctrine()->getManager();

          if ($categories != null)
            $findProduits = $em->getRepository('MickwebEcommerceBundle:Product')->byCategorie($categories);
          else 
            // $findProduits = $em->getRepository('MickwebEcommerceBundle:Product')->findBy(array('disponible' => 1));
            $findProduits = $em->getRepository('MickwebEcommerceBundle:Product')->findAllVisibleQuery($search);
            // ->getRepository('MickwebEcommerceBundle:Product')

        //   $listProducts = $repository->myFindAll();
        //   $listProducts = $repository->findBy(array('disponible' => 1));
        // $listProducts = $em->getRepository('MickwebEcommerceBundle:Product')->findBy(array('disponible' => 1));

        // Voir pour ajouter le Param converter pour les catégories
        // listener environ 22

          if($session->has('panier'))
            $panier = $session->get('panier');
          else
            $panier = false;

        // Le knp limite l'affichage à 9 produits
        $listProducts = $this->get('knp_paginator')->paginate($findProduits, $request->query->getInt('page', 1)/*page number*/,
            9/*limit per page*/);

          return $this->render('@MickwebEcommerce/Product/index.html.twig', array(
            'listProducts' => $listProducts,
            'panier' => $panier,
            'form' => $form->createView()
          ));
    }
/*******************************FICHE PRODUIT****************************************************************/
    public function ficheProduitAction($id, Request $request)
    {
        $session = $request->getSession();
        $em = $this->getDoctrine()->getManager();

        // je recupere le produit l'id
        $product = $em->getRepository('MickwebEcommerceBundle:Product')->find($id);
        $productAssoc = $em->getRepository('MickwebEcommerceBundle:Product')->byCategorie($product->getCategories());
        dump($productAssoc);
        // TODO: Revoir l'utilisation de categories
        // $categories = $em->getRepository('MickwebEcommerceBundle:Category')->findBy($id);

        // $product est donc une instance de Mickweb\EcommerceBundle\Entity\Product
        // ou null si l'id $id n'existe pas
        if (null === $product) {
            throw new NotFoundHttpException("Le produit d'id" .$id. "n'existe pas");
        }

        if($session->has('panier'))
            $panier = $session->get('panier');
          else
            $panier = false;

        // ajout d'un avis
        $listAvis = new Avis();
        // $form = $this->createForm('Mickweb\EcommerceBundle\Form\AvisType', $listAvis);
        $form = $this->get('form.factory')->create(AvisType::class, $listAvis);
        // $form->handleRequest($request);

        // if ($form->isSubmitted() && $form->isValid()) {
        if($request->isMethod('POST') && $form->handleRequest($request)->isValid()){
            $listAvis->setProduct($product);
            $em = $this->getDoctrine()->getManager();
            $em->persist($listAvis);
            $em->flush();

            return $this->redirectToRoute('mickweb_ecommerce_fiche_produit', array('id' => $product->getId()));
        }

        // je recupere la liste des avis de ce produit grace au findBy
          $afficheAvis = $em
            ->getRepository('MickwebEcommerceBundle:Avis')
            ->findBy(array('product' => $product))
          ;

        return $this->render('@MickwebEcommerce/Product/fiche_produit.html.twig', array(
            'product' => $product,
            // 'categories' => $categories,
            'form' => $form->createView(),
            'afficheAvis' => $afficheAvis,
            'productAssoc' => $productAssoc
        ));
    }

    /******************************* Avis client ****************************************************************/
    // public function avisProduitAction($id, Request $request)
    // {
       
    //     // ajout d'un avis
    //     $listAvis = new Avis();
    //     // $form = $this->createForm('Mickweb\EcommerceBundle\Form\AvisType', $listAvis);
    //     $form = $this->get('form.factory')->create(AvisType::class, $listAvis);
    //     // $form->handleRequest($request);

    //     // if ($form->isSubmitted() && $form->isValid()) {
    //     if($request->isMethod('POST') && $form->handleRequest($request)->isValid()){
    //         $em = $this->getDoctrine()->getManager();
    //         $em->persist($listAvis);
    //         $em->flush();

    //         return $this->redirectToRoute('mickweb_ecommerce_fiche_produit', array('id' => $listAvis->getId()));
    //     }

    //     // je recupere la liste des avis de ce produit grace au findBy
    //     //   $listAvis = $em
    //     //     ->getRepository('MickwebEcommerceBundle:Avis')
    //     //     ->findBy(array('product' => $product))
    //     //   ;

    //     return $this->render('@MickwebEcommerce/Product/fiche_produit.html.twig', array(
    //         'form' => $form->createView(),
    //         'listAvis' => $listAvis
    //     ));
    // }

/*******************************AJOUT PRODUIT****************************************************************/
    // Cette annonation sert à accéder à la page Ajout seulement aux Admin
    // Je l'ai désactivé pour le moment
    ///**
    //* @Security("has_role('ROLE_ADMIN')")
    //*
    //*/

    public function ajoutAction(Request $request)
    {
        // Condition qui donne accès à l'ajout des produits seulement aux ADMIN
        /*if (!$this->get('security.authorization_checker')->isGranted('ROLE_ADMIN')) {
          throw new AccessDeniedException('Accès réservé aux administrateurs du site');
        }*/


        /******************************************
         ******************************************
        // creation de l'entité product
        $product = new Product();
        $product->setTitre('T-shirt Ratifiole');
        $product->setAuteur('Mkl');
        $product->setDescription('T-shirt de qualité. Résiste aux hordes de métalleux, aux Wall of death et Circle pit');

        // Creation d'un 1er avis
        $avis1 = new Avis();
        $avis1->setCommentaire('Super produit, je recommande');
        $avis1->setNote(4);

        // Creation d'un 2eme avis
        $avis2 = new Avis();
        $avis2->setCommentaire('RAwwwww, royal, metal et casse-dalle');
        $avis2->setNote(4);

        // creation de l'entité Image
        $image = new Image();
        $image->setUrl('http://sdz-upload.s3.amazonaws.com/prod/upload/job-de-reve.jpg');
        $image->setAlt('Image palmier');

        // On lie l'image à l'annonce
        $avis1->setProduct($product);
        $avis2->setProduct($product);
        $product->setImage($image);

        //on récupère l'entityManager
        $em = $this->getDoctrine()->getManager();

        //1ere etape - On persiste l'entité
        $em->persist($product);
        $em->persist($avis1);
        $em->persist($avis2);
        // le fait d'avoir mis cascade "persist", l'entité $image est persisté automatiquement

        //2eme etape - on flush tout ce qui a été persisté avant
        $em->flush();

        ****************************************************/



        $product = new Product();

        // Avis en dur dans le code -- à supprimer par la suite
        // $avis1 = new Avis();
        // $avis1->setCommentaire('Super produit, je recommande');
        // $avis1->setNote(4);
        // $avis1->setProduct($product);

        // création du formbuilder grace au service form factory
        $form = $this->get('form.factory')->create(ProductType::class, $product);

       /* $formBuilder
            ->add('titre',          TextType::class)
            ->add('description',    TextareaType::class)
            ->add('auteur',         TextType::class)
            ->add('published',      CheckboxType::class, array('required' => false))
            ->add('save',           SubmitType::class)
        ;
        */

src/Mickweb/EcommerceBundle/Resources/views/Product/add.html.twig
{# src/Mickweb/EcommerceBundle/Resources/views/Advert/add.html.twig #}


{% extends "MickwebEcommerceBundle::layout.html.twig" %}

{% block title %}
    Ajouter un produit - {{ parent() }}
{% endblock %}

{% block MickwebEcommerce_body %}

  <h2>Ajouter un Produit</h2>

  {{ include("MickwebEcommerceBundle:Product:form.html.twig") }}

  <p>
    Attention : cette annonce sera ajoutée directement
    sur la page d'accueil après validation du formulaire.
  </p>

{#
  <p>
    <a href="{{ path('mickweb_ecommerce_fiche_produit', {'id': product.id}) }}" class="btn btn-default">
        <i class="glyphicon glyphicon-chevron-left"></i>
        Retour à la liste
    </a>
  </p>
#}

{% endblock %}

src/Mickweb/EcommerceBundle/Resources/views/Product/avis.html.twig
{# src/Mickweb/EcommerceBundle/Resources/views/Advert/avis.html.twig #}

src/Mickweb/EcommerceBundle/Resources/views/Product/categories.html.twig
{# src/Mickweb/EcommerceBundle/Resources/views/Product/index.html.twig #}

{% extends "MickwebEcommerceBundle::layout.html.twig" %}

{% block title %}
  Catégories - {{ parent() }}
{% endblock %}
{% block description %} {# description à ajouter #} {% endblock %}

{% block MickwebEcommerce_body %}
  
  <h1> Vous êtes dans la catégorie : {{ categories.name }}</h1>
  <hr>

    <div class="container col-sm-12">
      <div class="row">
          {% for product in produits %} {# produits ou listProducts #}
                <div class="col-sm-4">
                  <div>
                    <h4><a href="{{ path('mickweb_ecommerce_fiche_produit', {'id': product.id}) }}">
                    {{ product.titre }}
        
                  </a></h4>
                    <div>
                    {% if product.image %}
                    {# <img src="{{ product.image.url }}" alt="{{ product.image.alt }}"> #}
                      <img 
                        src="{{ asset(product.image.webPath) }}"
                        alt="{{ product.image.alt }}"
                        width="250" height="250"
                      />
                    {% endif %}
                    </div>
                    <p>{{ product.prix }} €</p>
                    {# <p>{{ product.prix|tva(product.tva.multiplicate) }} €</p> #}
                    <a class="button button5" href="{{ path('mickweb_ecommerce_fiche_produit', {'id': product.id}) }}">Plus d'infos</a>
                    <a class="buttonBasket button6" href="{{ path('ajouter_panier', {'id': product.id}) }}">Ajouter au panier</a>
                  </div>           
                </div>
          
                {% else %} 
                <p>Aucun produit disponible</p> 
          {% endfor %}  
      </div>
    </div>
    
  
{% endblock %}

src/Mickweb/EcommerceBundle/Resources/views/Product/index.html.twig
{# src/Mickweb/EcommerceBundle/Resources/views/Product/index.html.twig #}

{% extends "MickwebEcommerceBundle::layout.html.twig" %}

{% block title %}
  Accueil - {{ parent() }}
{% endblock %}
{% block description %} {# description à ajouter #} {% endblock %}

{% block MickwebEcommerce_body %}

  {% for flashMessage in app.session.flashbag.get('success') %}
      <div class="alert alert-success">{{ flashMessage }}</div>
  {% endfor %}

  <div class="container">
    <div class="jumbotron">

      {{ form_start(form) }}

      <div class="form-row">
        <div class="col-sm-4">
        {{ form_row(form.minPrice)}}
        </div>

        <div class="col-sm-4">
        {{ form_row(form.maxPrice)}}
        </div>
        
        <div class="col-sm-4">
          <div class="form-group">
            <button class="btn-recherche">Lancer la recherche</button>
          </div>
        </div>
      
      </div>
      {{ form_end(form)}}

    </div>
  </div>

  {# Système de filtre prix #}
  <div class="container col-sm-12">
      <div class="row">
        <div class="col-sm-4">
          <p>
            <label for="amount">Chercher un prix compris entre :</label>
            <input type="text" id="amount" readonly style="border:0; color:#f6931f; font-weight:bold;">
          </p>
          <div id="slider-range"></div>
        </div>

        <div class="col-sm-4">
          <div class="form-group">
              <label for="select-order">Trier les produits par :</label>
              <select class="form-control" id="select-order">
                  <option value="position">Prix le moins cher</option>
                  <option value="prix">Prix le plus cher</option>
                  <option value="name">Catégorie</option>
              </select>
          </div>
        </div>

        <div class="col-sm-4">
          <p>
            <label for="amount">Price range:</label>
            <input type="text" id="amount" readonly style="border:0; color:#f6931f; font-weight:bold;">
          </p>
        </div>
      </div>
  </div>

  <h2>Liste des produits</h2>
    <div class="container col-sm-12">
      <div class="row">
          {% for product in listProducts %} {# produits ou listProducts #}
                <div class="col-sm-4">
                  <div>
                      <div class="product-image">
                        {% if product.image %}
                        {# <img src="{{ product.image.url }}" alt="{{ product.image.alt }}"> #}
                          <img 
                            src="{{ asset(product.image.webPath) }}"
                            alt="{{ product.image.alt }}"
                            width="250" height="250"
                          />
                        {% endif %}
                      </div>

                      <div class="container col-sm-12 product-t-p">
                          <div class="row">
                              <div class="col-sm-6">
                                <h4 class="product-titre"><a href="{{ path('mickweb_ecommerce_fiche_produit', {'id': product.id}) }}">
                                {{ product.titre }}
                                </a></h4>
                              </div>
                              <div class="col-sm-6 product-prix">
                                <p>{{ product.prix }} €</p>
                                {# <p>{{ product.prix|tva(product.tva.multiplicate) }} €</p> #}
                              </div>
                          </div>
                      </div>

                      <div class="container col-sm-12 product-t-p">
                        <div class="row">
                          <div class="col-sm-6">
                            <a class="button button5" href="{{ path('mickweb_ecommerce_fiche_produit', {'id': product.id}) }}">Plus d'infos</a>
                            {% if panier[product.id] is not defined %}
                          </div>
                          <div class="col-sm-6">
                            <a class="buttonBasket button6" href="{{ path('ajouter_panier', {'id': product.id}) }}">Ajouter au panier</a>
                            {% else %}
                            <p class="buttonBasket buttondeja">Déjà dans votre panier</p>
                            {% endif %}
                          </div>
                        </div>
                      </div>
                        
                  </div>
                </div>           
              
                
                {% else %} 
                <p>Aucun produit disponible</p> 

          {% endfor %}
            <div class="navigation">
                {{ knp_pagination_render(listProducts) }}
            </div>
      </div>
    </div>
  
{% endblock %}

src/Mickweb/EcommerceBundle/Resources/views/Product/menu.html.twig
{# src/Mickweb/EcommerceBundle/Resources/views/Product/index.html.twig #}


{# Ce template n'hérite de personne,
   tout comme le template inclus avec {{ include() }}. #}

<ul class="nav nav-pills nav-stacked">

  {% for product in listProducts %}
    <li>
      <a href="{{ path('mickweb_ecommerce_fiche_produit', {'id': product.id}) }}">
        {{ product.titre }}
      </a>
    </li>
  {% endfor %}
</ul>

src/Mickweb/EcommerceBundle/Resources/views/Product/modifier.html.twig
{# src/Mickweb/EcommerceBundle/Resources/views/Advert/modifier.html.twig #}


{% extends "MickwebEcommerceBundle::layout.html.twig" %}

{% block title %}
    Modifier un produit - {{ parent() }}
{% endblock %}

{% block MickwebEcommerce_body %}

  <h2>Modifier un produit</h2>

  {{ include("MickwebEcommerceBundle:Product:form.html.twig") }}

  <p>
    Attention : ce produit existe déjà, merci de na pas changer l'esprit général de la description actuelle.
  </p>

{#
  <p>
    <a href="{{ path('mickweb_ecommerce_fiche_produit', {'id': product.id}) }}" class="btn btn-default">
        <i class="glyphicon glyphicon-chevron-left"></i>
        Retour à la liste
    </a>
  </p>
#}

{% endblock %}

src/Mickweb/EcommerceBundle/Resources/views/Product/pagecontact.html.twig
{% extends "MickwebEcommerceBundle::layout.html.twig" %}

{% block title %}
  Fiche produit - {{ parent() }}
{% endblock %}

{% block MickwebEcommerce_body %}

<div class="container col-md-12">
	<div class="row">

		{% for flashMessage in app.session.flashbag.get('success') %}
			<div class="alert alert-success">
				{{ flashMessage }}
			</div>
		{% endfor %}
					
		<h1> Bienvenue sur la page de contact </h1>
		<div class="col-md-6">
			<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2625.271656953916!2d2.4011593152452635!3d48.85302997928704!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e67278f86e2fb5%3A0xcab144bf83eb445e!2s5+Rue+de+la+R%C3%A9union%2C+75020+Paris!5e0!3m2!1sfr!2sfr!4v1551385044027" width="470" height="320" frameborder="0" style="border:0" allowfullscreen></iframe>
		</div>
		<div class="col-md-6">
			<div id="contactForm" class="mt-4">
				{{ form_start(form) }}
				<div class="row">
					<div class="col-sm-4"> {{ form_row(form.firstname) }} </div>
					<div class="col-sm-4"> {{ form_row(form.lastname) }} </div>
				</div>
				<div class="row">
					<div class="col-sm-4"> {{ form_row(form.phone) }} </div>
					<div class="col-sm-4"> {{ form_row(form.email) }} </div>
				</div>
				{{form_rest(form)}}
				<div class="form-group">
					<button class="btn recherche">Envoyer</button>
				</div>
		
				{{ form_end(form) }}
			</div>
		</div>
			
	</div>
</div>

{% endblock %}

src/Mickweb/EcommerceBundle/Resources/views/Product/supprimer.html.twig
{# src/Mickweb/EcommerceBundle/Resources/views/Advert/supprimer.html.twig #}


{% extends "MickwebEcommerceBundle::layout.html.twig" %}

{% block title %}
    Supprimer un produit - {{ parent() }}
{% endblock %}

{% block MickwebEcommerce_body %}

  <h2>Supprimer un Produit</h2>

  <p> 
    Etes-vous certains de vouloir supprimer l'annonce "{{ product.titre }}" ?
  </p>

  {# l'id de l'annonce est dans la route de l'action du formulaire #}
  <form action="{{ path('mickweb_ecommerce_supprimer', {'id': product.id}) }}" method="post">
    <a href="{{ path('mickweb_ecommerce_fiche_produit', {'id': product.id}) }}" class="btn btn-default">
      <i class="glyphicon glyphicon-chevron-left"></i>
          Retour à la liste
    </a>
    {# bouton de soumission #}
    <input type="submit" value="Supprimer" class="btn btn-danger" />
    {# génération du champ CSRF #}
    {{ form_rest(form) }}
  </form>

{#
  <p>
    <a href="{{ path('mickweb_ecommerce_fiche_produit', {'id': product.id}) }}" class="btn btn-default">
        <i class="glyphicon glyphicon-chevron-left"></i>
        Retour à la liste
    </a>
  </p>
#}

{% endblock %}